---
name: chatgpt
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.17.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.8.0 
  cloud_functions: 4.7.6
  webview_flutter: 4.8.0
  url_launcher: ^6.3.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.0.8
  cookie_jar: ^4.0.8
  uuid: ^4.4.2
  device_info_plus: ^10.1.2
  flutter_stripe: ^11.0.0
  http: ^1.2.2
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  flutter_spinkit: ^5.1.0
  chat_gpt_flutter: ^1.0.6
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  build_runner: ^2.3.3
  flutter_bloc: ^8.1.2
  animated_text_kit: ^4.2.1
  shared_preferences_web: ^2.4.2
  flutter_web_plugins:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.3.0
  freezed: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/google.png
    - assets/icons/facebook.png
    - assets/  # Mantiene la carpeta completa accesible

  fonts:
    - family: Nud
      fonts:
        - asset: assets/fonts/nud.ttf
