// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz92fJp2d1Iu0QCcApVjRvj8K_j_co7Tc',
    appId: '1:746779309482:web:d901d07f4125622e6827d3',
    messagingSenderId: '746779309482',
    projectId: 'chattdp-b2ab5',
    authDomain: 'chattdp-b2ab5.firebaseapp.com',
    storageBucket: 'chattdp-b2ab5.appspot.com',
    measurementId: 'G-E383CY9ZPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcwv0fTtoAwNmfzfYBxJVKl-hU6aJCFzY',
    appId: '1:746779309482:android:b24d230238fff0c96827d3',
    messagingSenderId: '746779309482',
    projectId: 'chattdp-b2ab5',
    storageBucket: 'chattdp-b2ab5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAl9E7bnc8Cl4mbhIVxlaur6AbPkaGuAE',
    appId: '1:746779309482:ios:e741d6074fc22dc66827d3',
    messagingSenderId: '746779309482',
    projectId: 'chattdp-b2ab5',
    storageBucket: 'chattdp-b2ab5.appspot.com',
    iosClientId: '746779309482-15lu87hsqeq6te44kkndtbjb4otfeckd.apps.googleusercontent.com',
    iosBundleId: 'com.jagoteori.chatgpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAl9E7bnc8Cl4mbhIVxlaur6AbPkaGuAE',
    appId: '1:746779309482:ios:e741d6074fc22dc66827d3',
    messagingSenderId: '746779309482',
    projectId: 'chattdp-b2ab5',
    storageBucket: 'chattdp-b2ab5.appspot.com',
    iosClientId: '746779309482-15lu87hsqeq6te44kkndtbjb4otfeckd.apps.googleusercontent.com',
    iosBundleId: 'com.jagoteori.chatgpt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz92fJp2d1Iu0QCcApVjRvj8K_j_co7Tc',
    appId: '1:746779309482:web:6fd320c7989d07fe6827d3',
    messagingSenderId: '746779309482',
    projectId: 'chattdp-b2ab5',
    authDomain: 'chattdp-b2ab5.firebaseapp.com',
    storageBucket: 'chattdp-b2ab5.appspot.com',
    measurementId: 'G-V6SSE7Q28Y',
  );
}
